### Add students
POST http://localhost:3000/students
content-type: application/json

{
    "name": "Mathew",
    "registrationNo": "CT98KA"
}

### Get All students
GET http://localhost:3000/students


### Add course
POST http://localhost:3000/courses
content-type: application/json

{
    "name": "Data Science"
}

### Get All courses
GET http://localhost:3000/courses


### Enroll multiple courses to a student
POST http://localhost:3000/enrollment/2/courses
content-type: application/json

[
  {
    "course": { "id": 2, "name": "ML"},
    "levelId": 1
  },
  {
    "course": { "id": 3, "name": "Data Science"},
    "levelId": 2
  },
  {
    "course": { "id": 2, "name": "ML"},
    "levelId": 1
  }
]
